### ISSUE TITLE
Invalid attempt to destructure non-iterable instance

### ISSUE THREAD

**Issue by RyanRizzo96** [olivierlando/path-from-image#1]
I keep getting this error on a basic project build : Uncaught TypeError: Invalid attempt to destructure non-iterable instance

On closer inspection, this error is being generated from:

`var _slicedToArray = function () { function sliceIterator(arr, i) { var _arr = []; var _n = true; var _d = false; var _e = undefined; try { for (var _i = arr[Symbol.iterator](), _s; !(_n = (_s = _i.next()).done); _n = true) { _arr.push(_s.value); if (i && _arr.length === i) break; } } catch (err) { _d = true; _e = err; } finally { try { if (!_n && _i["return"]) _i["return"](); } finally { if (_d) throw _e; } } return _arr; } return function (arr, i) { if (Array.isArray(arr)) { return arr; } else if (Symbol.iterator in Object(arr)) { return sliceIterator(arr, i); } else { throw new TypeError("Invalid attempt to destructure non-iterable instance"); } }; }();`

in the `PathFromImage.js` file.

It seems like:

               value: function path(_ref, _ref2, tolerance) {
               var _ref4 = _slicedToArray(_ref, 2),
               x1 = _ref4[0],
               y1 = _ref4[1];

is the root cause, specifically line 2.

Any ideas on how can this be resolved? Thanks

**Comment by olivierlando** [comment]
Thanks for your message. I'm going to have a look.

**Comment by RyanRizzo96** [comment]
Hi @Olivierlando, there was a mistake on my part, sorry for the confusion!
